# generated by datamodel-codegen:
#   filename:  session.schema.json
#   timestamp: 2026-03-02T22:38:52+00:00

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from enum import Enum


class UUID(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="UUID v4 format",
            pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
        ),
    ]


class ISO8601Timestamp(RootModel[AwareDatetime]):
    root: Annotated[AwareDatetime, Field(description="ISO-8601 timestamp")]


class CLIVersion(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="CLI version string (semver)",
            examples=["2.0.62", "2.0.76", "2.1.1", "2.1.59"],
            pattern="^\\d+\\.\\d+\\.\\d+$",
        ),
    ]


class ModelId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Claude model identifier",
            examples=[
                "claude-opus-4-5-20251101",
                "claude-opus-4-6",
                "claude-sonnet-4-5-20250929",
                "claude-sonnet-4-6",
                "claude-haiku-4-5-20251001",
                "<synthetic>",
            ],
        ),
    ]


class BuiltInToolName(Enum):
    Bash = "Bash"
    Read = "Read"
    Write = "Write"
    Edit = "Edit"
    Glob = "Glob"
    Grep = "Grep"
    WebSearch = "WebSearch"
    WebFetch = "WebFetch"
    Task = "Task"
    TaskOutput = "TaskOutput"
    TaskStop = "TaskStop"
    TaskCreate = "TaskCreate"
    TaskUpdate = "TaskUpdate"
    TaskList = "TaskList"
    TaskGet = "TaskGet"
    TodoWrite = "TodoWrite"
    AskUserQuestion = "AskUserQuestion"
    NotebookEdit = "NotebookEdit"
    EnterPlanMode = "EnterPlanMode"
    ExitPlanMode = "ExitPlanMode"
    EnterWorktree = "EnterWorktree"
    Skill = "Skill"
    KillShell = "KillShell"
    ToolSearch = "ToolSearch"
    SendMessage = "SendMessage"
    TeamCreate = "TeamCreate"
    TeamDelete = "TeamDelete"
    ListMcpResourcesTool = "ListMcpResourcesTool"
    ReadMcpResourceTool = "ReadMcpResourceTool"
    Agent = "Agent"


class MCPToolName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="MCP tool name pattern: mcp__<server>__<tool>. Server names may contain colons (e.g., plugin:sentry:sentry).",
            pattern="^mcp__[a-zA-Z0-9_:-]+__[a-zA-Z0-9_-]+$",
        ),
    ]


class ToolName(RootModel[BuiltInToolName | MCPToolName]):
    root: Annotated[
        BuiltInToolName | MCPToolName, Field(description="Tool name (built-in or MCP)")
    ]


class BashInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    command: Annotated[str, Field(description="The bash command to execute")]
    description: Annotated[
        str | None, Field(description="Short description of command purpose")
    ] = None
    timeout: Annotated[
        float | None, Field(description="Timeout in milliseconds", ge=0.0, le=600000.0)
    ] = None
    run_in_background: Annotated[
        bool | None, Field(description="Run command in background")
    ] = None
    dangerouslyDisableSandbox: Annotated[
        bool | None, Field(description="Disable sandbox mode")
    ] = None


class ReadInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_path: Annotated[str, Field(description="Absolute path to file")]
    offset: Annotated[
        int | None, Field(description="Line number to start reading from", ge=0)
    ] = None
    limit: Annotated[int | None, Field(description="Number of lines to read", ge=1)] = (
        None
    )
    pages: Annotated[
        str | None, Field(description="Page range for PDF files (e.g., '1-5')")
    ] = None


class WriteInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_path: Annotated[str, Field(description="Absolute path to file")]
    content: Annotated[str, Field(description="Content to write")]


class EditInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_path: Annotated[str, Field(description="Absolute path to file")]
    old_string: Annotated[str, Field(description="Text to replace")]
    new_string: Annotated[str, Field(description="Replacement text")]
    replace_all: Annotated[
        bool | None, Field(description="Replace all occurrences")
    ] = False


class GlobInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pattern: Annotated[str, Field(description="Glob pattern to match")]
    path: Annotated[str | None, Field(description="Directory to search in")] = None


class OutputMode(Enum):
    content = "content"
    files_with_matches = "files_with_matches"
    count = "count"


class GrepInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pattern: Annotated[str, Field(description="Regex pattern to search")]
    path: Annotated[str | None, Field(description="File or directory to search")] = None
    output_mode: OutputMode | None = None
    glob: Annotated[str | None, Field(description="Glob pattern to filter files")] = (
        None
    )
    type: Annotated[
        str | None, Field(description="File type to search (e.g., js, py)")
    ] = None
    head_limit: Annotated[int | None, Field(description="Limit output lines", ge=0)] = (
        None
    )
    offset: Annotated[int | None, Field(description="Skip first N lines", ge=0)] = None
    multiline: Annotated[bool | None, Field(description="Enable multiline mode")] = None
    context: Annotated[
        int | None, Field(description="Lines of context (alias for -C)", ge=0)
    ] = None
    field_A: Annotated[
        int | None, Field(alias="-A", description="Lines after match", ge=0)
    ] = None
    field_B: Annotated[
        int | None, Field(alias="-B", description="Lines before match", ge=0)
    ] = None
    field_C: Annotated[
        int | None, Field(alias="-C", description="Lines of context", ge=0)
    ] = None
    field_i: Annotated[
        bool | None, Field(alias="-i", description="Case insensitive")
    ] = None
    field_n: Annotated[
        bool | None, Field(alias="-n", description="Show line numbers")
    ] = None


class WebSearchInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: Annotated[str, Field(description="Search query", min_length=2)]
    allowed_domains: Annotated[
        list[str] | None, Field(description="Domains to include")
    ] = None
    blocked_domains: Annotated[
        list[str] | None, Field(description="Domains to exclude")
    ] = None


class WebFetchInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[AnyUrl, Field(description="URL to fetch")]
    prompt: Annotated[str, Field(description="Prompt for processing content")]


class Model(Enum):
    sonnet = "sonnet"
    opus = "opus"
    haiku = "haiku"


class Mode(Enum):
    acceptEdits = "acceptEdits"
    bypassPermissions = "bypassPermissions"
    default = "default"
    dontAsk = "dontAsk"
    plan = "plan"


class TaskInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Annotated[str, Field(description="Short task description (3-5 words)")]
    prompt: Annotated[str, Field(description="Task prompt for agent")]
    subagent_type: Annotated[
        str,
        Field(
            description="Type of agent to use (e.g., general-purpose, Explore, Plan)"
        ),
    ]
    run_in_background: Annotated[
        bool | None, Field(description="Run agent in background")
    ] = None
    model: Annotated[Model | None, Field(description="Model override for subagent")] = (
        None
    )
    resume: Annotated[str | None, Field(description="Agent ID to resume")] = None
    name: Annotated[
        str | None,
        Field(
            description="Named agent identifier (used with team_name for team members)"
        ),
    ] = None
    team_name: Annotated[
        str | None, Field(description="Team to join (links to TeamCreate)")
    ] = None
    mode: Annotated[
        Mode | None, Field(description="Permission mode for spawned agent")
    ] = None
    max_turns: Annotated[
        int | None,
        Field(
            description="Max agentic turns before stopping", gt=0, le=9007199254740991
        ),
    ] = None
    isolation: Annotated[
        Literal["worktree"] | None,
        Field(description="Isolation mode — worktree creates a temporary git worktree"),
    ] = None


class Status(Enum):
    pending = "pending"
    in_progress = "in_progress"
    completed = "completed"


class TodoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: Annotated[
        str, Field(description="Task description (imperative form)", min_length=1)
    ]
    status: Status
    activeForm: Annotated[
        str, Field(description="Present continuous form", min_length=1)
    ]


class TodoWriteInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    todos: Annotated[list[TodoItem], Field(description="Updated todo list")]


class QuestionOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: Annotated[str, Field(description="Display text for option")]
    description: Annotated[str, Field(description="Explanation of option")]
    markdown: Annotated[
        str | None, Field(description="Preview content shown when option is focused")
    ] = None


class Question(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    question: Annotated[str, Field(description="The question to ask")]
    header: Annotated[
        str, Field(description="Short label (max 12 chars)", max_length=12)
    ]
    options: Annotated[list[QuestionOption], Field(max_length=4, min_length=2)]
    multiSelect: bool


class Annotations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    markdown: Annotated[
        str | None, Field(description="Markdown preview content of the selected option")
    ] = None
    notes: Annotated[
        str | None,
        Field(description="Free-text notes the user added to their selection"),
    ] = None


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Annotated[
        str | None, Field(description="Source identifier (e.g., 'remember')")
    ] = None


class AskUserQuestionInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    questions: Annotated[list[Question], Field(max_length=4, min_length=1)]
    answers: Annotated[dict[str, str] | None, Field(description="User answers")] = None
    annotations: Annotated[
        dict[str, Annotations] | None,
        Field(description="Per-question annotations keyed by question text"),
    ] = None
    metadata: Annotated[
        Metadata | None, Field(description="Tracking/analytics metadata")
    ] = None


class CellType(Enum):
    code = "code"
    markdown = "markdown"


class EditMode(Enum):
    replace = "replace"
    insert = "insert"
    delete = "delete"


class NotebookEditInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    notebook_path: Annotated[str, Field(description="Absolute path to notebook")]
    new_source: Annotated[str, Field(description="New cell source")]
    cell_id: Annotated[str | None, Field(description="Cell ID to edit")] = None
    cell_type: CellType | None = None
    edit_mode: EditMode | None = None


class EnterPlanModeInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class AllowedPrompt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool: Annotated[Literal["Bash"], Field(description="Tool this prompt applies to")]
    prompt: Annotated[
        str, Field(description="Semantic description of the allowed action")
    ]


class ExitPlanModeInput(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    plan: Annotated[str | None, Field(description="Plan content")] = None
    allowedPrompts: Annotated[
        list[AllowedPrompt] | None,
        Field(description="Prompt-based permissions needed to implement the plan"),
    ] = None


class SkillInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skill: Annotated[str, Field(description="Skill name to invoke")]
    args: Annotated[str | None, Field(description="Optional arguments")] = None


class KillShellInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shell_id: Annotated[str, Field(description="ID of shell to kill")]


class TaskOutputInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: Annotated[str, Field(description="Task ID to get output from")]
    block: Annotated[bool, Field(description="Wait for completion")]
    timeout: Annotated[
        float, Field(description="Max wait time in ms", ge=0.0, le=600000.0)
    ]


class TaskStopInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task_id: Annotated[str | None, Field(description="Background task ID to stop")] = (
        None
    )
    shell_id: Annotated[
        str | None, Field(description="Deprecated: use task_id instead")
    ] = None


class ToolSearchInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: Annotated[
        str,
        Field(
            description="Keyword search or 'select:<tool_name>' for direct selection"
        ),
    ]
    max_results: Annotated[
        float, Field(description="Maximum results to return", ge=1.0)
    ]


class Type(Enum):
    message = "message"
    broadcast = "broadcast"
    shutdown_request = "shutdown_request"
    shutdown_response = "shutdown_response"
    plan_approval_response = "plan_approval_response"


class SendMessageInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[Type, Field(description="Message type")]
    recipient: Annotated[
        str | None,
        Field(
            description="Agent name of recipient (for message, shutdown_request, plan_approval_response)"
        ),
    ] = None
    content: Annotated[
        str | None, Field(description="Message text, reason, or feedback")
    ] = None
    summary: Annotated[
        str | None,
        Field(
            description="5-10 word summary shown as UI preview (for message, broadcast)"
        ),
    ] = None
    request_id: Annotated[
        str | None,
        Field(
            description="Request ID to respond to (for shutdown_response, plan_approval_response)"
        ),
    ] = None
    approve: Annotated[
        bool | None,
        Field(
            description="Whether to approve (for shutdown_response, plan_approval_response)"
        ),
    ] = None


class TaskCreateInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject: Annotated[str, Field(description="Brief task title (imperative form)")]
    description: Annotated[
        str,
        Field(description="Detailed description with context and acceptance criteria"),
    ]
    activeForm: Annotated[
        str | None, Field(description="Present continuous form shown in spinner")
    ] = None
    metadata: Annotated[
        dict[str, Any] | None, Field(description="Arbitrary metadata")
    ] = None


class Status1(Enum):
    pending = "pending"
    in_progress = "in_progress"
    completed = "completed"
    deleted = "deleted"


class TaskUpdateInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    taskId: Annotated[str, Field(description="Task ID to update")]
    status: Annotated[Status1 | None, Field(description="New task status")] = None
    subject: Annotated[str | None, Field(description="New task title")] = None
    description: Annotated[str | None, Field(description="New task description")] = None
    activeForm: Annotated[str | None, Field(description="Present continuous form")] = (
        None
    )
    owner: Annotated[str | None, Field(description="Agent name to assign")] = None
    metadata: Annotated[
        dict[str, Any] | None, Field(description="Metadata to merge")
    ] = None
    addBlocks: Annotated[
        list[str] | None, Field(description="Task IDs this task blocks")
    ] = None
    addBlockedBy: Annotated[
        list[str] | None, Field(description="Task IDs that block this task")
    ] = None


class TaskListInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class TaskGetInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    taskId: Annotated[str, Field(description="Task ID to retrieve")]


class TeamCreateInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    team_name: Annotated[str, Field(description="Slug/identifier for the team")]
    description: Annotated[str | None, Field(description="Team purpose")] = None
    agent_type: Annotated[
        str | None, Field(description="Role of the calling agent in the team")
    ] = None


class TeamDeleteInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class EnterWorktreeInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str | None, Field(description="Optional name for the worktree")] = (
        None
    )


class ListMcpResourcesInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server: Annotated[
        str | None, Field(description="Optional server name to filter by")
    ] = None


class ReadMcpResourceInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server: Annotated[str, Field(description="MCP server name")]
    uri: Annotated[str, Field(description="Resource URI to read")]


class MCPToolInput(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class ToolInput(
    RootModel[
        BashInput
        | ReadInput
        | WriteInput
        | EditInput
        | GlobInput
        | GrepInput
        | WebSearchInput
        | WebFetchInput
        | TaskInput
        | TaskOutputInput
        | TaskStopInput
        | ToolSearchInput
        | SendMessageInput
        | TaskCreateInput
        | TaskUpdateInput
        | TaskListInput
        | TaskGetInput
        | TeamCreateInput
        | TeamDeleteInput
        | EnterWorktreeInput
        | ListMcpResourcesInput
        | ReadMcpResourceInput
        | TodoWriteInput
        | AskUserQuestionInput
        | NotebookEditInput
        | EnterPlanModeInput
        | ExitPlanModeInput
        | SkillInput
        | KillShellInput
        | MCPToolInput
    ]
):
    root: Annotated[
        BashInput
        | ReadInput
        | WriteInput
        | EditInput
        | GlobInput
        | GrepInput
        | WebSearchInput
        | WebFetchInput
        | TaskInput
        | TaskOutputInput
        | TaskStopInput
        | ToolSearchInput
        | SendMessageInput
        | TaskCreateInput
        | TaskUpdateInput
        | TaskListInput
        | TaskGetInput
        | TeamCreateInput
        | TeamDeleteInput
        | EnterWorktreeInput
        | ListMcpResourcesInput
        | ReadMcpResourceInput
        | TodoWriteInput
        | AskUserQuestionInput
        | NotebookEditInput
        | EnterPlanModeInput
        | ExitPlanModeInput
        | SkillInput
        | KillShellInput
        | MCPToolInput,
        Field(description="Tool-specific input parameters"),
    ]


class TextBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["text"]
    text: str


class ThinkingBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["thinking"]
    thinking: Annotated[str, Field(description="Claude's reasoning")]
    signature: Annotated[str, Field(description="Cryptographic signature (base64)")]


class ToolUseCaller(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Annotated[str, Field(description="Caller type (e.g., 'direct')")]


class ToolUseBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["tool_use"]
    id: Annotated[str, Field(description="Tool use ID", pattern="^toolu_[a-zA-Z0-9]+$")]
    name: ToolName
    input: Annotated[dict[str, Any], Field(description="Tool-specific input")]
    caller: ToolUseCaller | None = None


class ToolReferenceBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["tool_reference"]
    tool_name: Annotated[str, Field(description="Name of the referenced tool")]


class ToolResultContentItem1(BaseModel):
    type: Literal["text"]
    text: str


class MediaType(Enum):
    image_png = "image/png"
    image_jpeg = "image/jpeg"
    image_gif = "image/gif"
    image_webp = "image/webp"


class Source(BaseModel):
    type: Literal["base64"]
    media_type: MediaType
    data: str


class ToolResultContentItem2(BaseModel):
    type: Literal["image"]
    source: Source


class ToolResultContentItem(
    RootModel[
        str | ToolResultContentItem1 | ToolResultContentItem2 | ToolReferenceBlock
    ]
):
    root: str | ToolResultContentItem1 | ToolResultContentItem2 | ToolReferenceBlock


class ToolResultBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["tool_result"]
    tool_use_id: Annotated[str, Field(pattern="^toolu_[a-zA-Z0-9]+$")]
    content: str | list[ToolResultContentItem]
    is_error: bool | None = None


class Source1(BaseModel):
    type: Literal["base64"]
    media_type: MediaType
    data: str


class ImageBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["image"]
    source: Source1


class Source2(BaseModel):
    type: Literal["base64"]
    media_type: Literal["application/pdf"]
    data: str


class DocumentBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["document"]
    source: Source2


class ContentBlock(
    RootModel[
        TextBlock
        | ThinkingBlock
        | ToolUseBlock
        | ToolResultBlock
        | ImageBlock
        | DocumentBlock
        | ToolReferenceBlock
    ]
):
    root: (
        TextBlock
        | ThinkingBlock
        | ToolUseBlock
        | ToolResultBlock
        | ImageBlock
        | DocumentBlock
        | ToolReferenceBlock
    )


class Level(Enum):
    high = "high"
    medium = "medium"
    low = "low"


class ThinkingMetadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    level: Level | None = None
    disabled: bool | None = None
    triggers: list[str] | None = None


class CacheCreation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ephemeral_5m_input_tokens: int | None = None
    ephemeral_1h_input_tokens: int | None = None


class ServerToolUse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    web_search_requests: int | None = None
    web_fetch_requests: int | None = None


class UsageInfo(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int, Field(ge=0)]
    cache_creation_input_tokens: Annotated[int | None, Field(ge=0)] = None
    cache_read_input_tokens: Annotated[int | None, Field(ge=0)] = None
    cache_creation: CacheCreation | None = None
    service_tier: str | None = None
    server_tool_use: ServerToolUse | None = None
    inference_geo: Annotated[
        str | None,
        Field(
            description="Inference geographic region (e.g., 'not_available', empty string, or null)"
        ),
    ] = None
    iterations: Annotated[
        list[dict[str, Any]] | None,
        Field(description="Iteration details (observed as empty array or null)"),
    ] = None
    speed: Annotated[
        str | None,
        Field(description="Inference speed tier (e.g., 'standard', or null)"),
    ] = None


class UserMessageContent(RootModel[str | list[ContentBlock]]):
    root: Annotated[
        str | list[ContentBlock],
        Field(
            description="User message content - string when isCompactSummary, array otherwise"
        ),
    ]


class Message(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    role: Literal["user"]
    content: UserMessageContent


class PermissionMode(Enum):
    default = "default"
    acceptEdits = "acceptEdits"
    bypassPermissions = "bypassPermissions"
    dontAsk = "dontAsk"
    plan = "plan"


class UserMessage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["user"]
    uuid: UUID
    parentUuid: UUID | None
    sessionId: UUID
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: Annotated[str, Field(description="Current working directory")]
    gitBranch: Annotated[str | None, Field(description="Git branch name")] = None
    isSidechain: bool
    userType: Literal["external"]
    message: Message
    thinkingMetadata: ThinkingMetadata | None = None
    todos: list[TodoItem] | None = None
    isMeta: bool | None = None
    isCompactSummary: Annotated[
        bool | None, Field(description="When true, content is summary string")
    ] = None
    isVisibleInTranscriptOnly: Annotated[
        bool | None,
        Field(
            description="Message visible in transcript but not sent to model (v2.1.x+)"
        ),
    ] = None
    agentId: Annotated[
        str | None, Field(description="Agent ID (in agent session files)")
    ] = None
    slug: Annotated[str | None, Field(description="Human-readable session name")] = None
    toolUseResult: Annotated[
        dict[str, Any] | str | list[ToolResultContentItem] | None,
        Field(
            description="Tool result metadata (v2.1.1+) — can be object, string, or array of content items"
        ),
    ] = None
    sourceToolAssistantUUID: Annotated[
        UUID | None,
        Field(description="UUID of assistant message that triggered tool (v2.1.1+)"),
    ] = None
    permissionMode: Annotated[
        PermissionMode | None,
        Field(description="Active permission mode for this turn (v2.1.x+)"),
    ] = None
    teamName: Annotated[
        str | None,
        Field(description="Team name when operating in a team context (v2.1.x+)"),
    ] = None
    imagePasteIds: Annotated[
        list[str | int] | None, Field(description="IDs of pasted images (v2.1.x+)")
    ] = None


class StopReason(Enum):
    end_turn = "end_turn"
    tool_use = "tool_use"
    max_tokens = "max_tokens"
    stop_sequence = "stop_sequence"


class Message1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    model: ModelId
    id: Annotated[
        str, Field(description="API message ID (msg_* pattern or UUID for synthetic)")
    ]
    type: Literal["message"]
    role: Literal["assistant"]
    content: list[ContentBlock]
    stop_reason: StopReason | None
    stop_sequence: str | None
    usage: UsageInfo


class AssistantMessage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["assistant"]
    uuid: UUID
    parentUuid: UUID | None
    sessionId: UUID
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: str
    gitBranch: str | None = None
    isSidechain: bool
    userType: Literal["external"]
    requestId: Annotated[
        str | None, Field(description="API request ID", pattern="^req_[a-zA-Z0-9]+$")
    ] = None
    message: Message1
    agentId: str | None = None
    slug: str | None = None
    isApiErrorMessage: Annotated[
        bool | None, Field(description="Whether this is an API error message")
    ] = None
    error: Annotated[str | None, Field(description="Error type (e.g., rate_limit)")] = (
        None
    )
    teamName: Annotated[
        str | None,
        Field(description="Team name when operating in a team context (v2.1.x+)"),
    ] = None


class Subtype(Enum):
    local_command = "local_command"
    turn_duration = "turn_duration"
    api_error = "api_error"
    stop_hook_summary = "stop_hook_summary"
    compact_boundary = "compact_boundary"
    microcompact_boundary = "microcompact_boundary"
    bridge_status = "bridge_status"


class Level1(Enum):
    info = "info"
    warn = "warn"
    error = "error"
    suggestion = "suggestion"


class CompactMetadata(BaseModel):
    trigger: str | None = None
    preTokens: int | None = None


class MicrocompactMetadata(BaseModel):
    trigger: str | None = None
    preTokens: int | None = None
    tokensSaved: int | None = None
    compactedToolIds: list[str] | None = None
    clearedAttachmentUUIDs: list[str] | None = None


class Cause(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: Annotated[
        str | None,
        Field(
            description="Error code (e.g., ECONNRESET, ConnectionRefused, FailedToOpenSocket)"
        ),
    ] = None
    path: Annotated[str | None, Field(description="Request URL")] = None
    errno: int | None = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    cause: Cause | None = None


class Cause1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: Annotated[
        str | None,
        Field(description="Error code (e.g., ConnectionRefused, FailedToOpenSocket)"),
    ] = None
    path: Annotated[str | None, Field(description="Request URL path")] = None
    errno: int | None = None


class SystemMessage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["system"]
    uuid: UUID
    parentUuid: UUID | None
    sessionId: UUID
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: str
    gitBranch: str | None = None
    isSidechain: bool
    userType: Literal["external"]
    subtype: Annotated[
        Subtype,
        Field(
            description="System message subtype. microcompact_boundary added in v2.1.63."
        ),
    ]
    content: Annotated[str | None, Field(description="Message content")] = None
    level: Level1 | None = None
    durationMs: Annotated[
        int | None, Field(description="Duration in milliseconds", ge=0)
    ] = None
    isMeta: bool | None = None
    agentId: str | None = None
    slug: str | None = None
    hookCount: Annotated[
        int | None, Field(description="Number of hooks triggered (stop_hook_summary)")
    ] = None
    hookInfos: Annotated[
        list[dict[str, Any]] | None,
        Field(description="Hook information (stop_hook_summary)"),
    ] = None
    hookErrors: Annotated[
        list[dict[str, Any] | str] | None,
        Field(description="Hook errors (stop_hook_summary)"),
    ] = None
    preventedContinuation: Annotated[
        bool | None, Field(description="Whether hook prevented continuation")
    ] = None
    stopReason: Annotated[str | None, Field(description="Reason for stop")] = None
    hasOutput: Annotated[bool | None, Field(description="Whether there is output")] = (
        None
    )
    toolUseID: Annotated[str | None, Field(description="Tool use ID")] = None
    logicalParentUuid: Annotated[
        UUID | None, Field(description="Logical parent UUID (compact_boundary)")
    ] = None
    compactMetadata: Annotated[
        CompactMetadata | None, Field(description="Compact metadata (compact_boundary)")
    ] = None
    microcompactMetadata: Annotated[
        MicrocompactMetadata | None,
        Field(
            description="Microcompact metadata (microcompact_boundary). Added in v2.1.63."
        ),
    ] = None
    teamName: Annotated[
        str | None, Field(description="Team name when in team context (v2.1.x+)")
    ] = None
    error: Annotated[
        Error | None,
        Field(
            description="Error details (api_error subtype). Contains cause object mirroring the top-level cause field."
        ),
    ] = None
    url: Annotated[
        AnyUrl | None,
        Field(
            description="URL for bridge_status subtype (remote control session link)"
        ),
    ] = None
    cause: Annotated[
        str | Cause1 | None,
        Field(
            description="Error cause — string or object with code/path/errno (api_error retry metadata)"
        ),
    ] = None
    retryInMs: Annotated[
        float | None,
        Field(description="Retry delay in milliseconds (can be fractional)", ge=0.0),
    ] = None
    retryAttempt: Annotated[
        int | None, Field(description="Current retry attempt number", ge=0)
    ] = None
    maxRetries: Annotated[
        int | None, Field(description="Maximum retry attempts", ge=0)
    ] = None


class SummaryMessage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["summary"]
    summary: Annotated[str, Field(description="Human-readable conversation summary")]
    leafUuid: Annotated[UUID, Field(description="UUID of last summarized message")]


class FileBackupInfo(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    originalContent: Annotated[
        str | None, Field(description="Original file content (legacy)")
    ] = None
    path: Annotated[str | None, Field(description="File path (legacy)")] = None
    backupFileName: Annotated[
        str | None, Field(description="Backup file identifier")
    ] = None
    version: Annotated[int | None, Field(description="Backup version number", ge=1)] = (
        None
    )
    backupTime: Annotated[
        ISO8601Timestamp | None, Field(description="Backup timestamp")
    ] = None


class Snapshot(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    messageId: UUID
    trackedFileBackups: Annotated[
        dict[str, FileBackupInfo], Field(description="Map of file path to backup info")
    ]
    timestamp: ISO8601Timestamp


class FileHistorySnapshot(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["file-history-snapshot"]
    messageId: UUID
    snapshot: Snapshot
    isSnapshotUpdate: bool


class Operation(Enum):
    enqueue = "enqueue"
    remove = "remove"
    dequeue = "dequeue"
    popAll = "popAll"


class QueueOperation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["queue-operation"]
    operation: Operation
    timestamp: ISO8601Timestamp
    sessionId: UUID
    content: Annotated[
        str | None, Field(description="Message content (for enqueue)")
    ] = None


class Status2(Enum):
    started = "started"
    completed = "completed"
    failed = "failed"


class MCPProgressData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["mcp_progress"]
    status: Status2
    serverName: Annotated[
        str,
        Field(
            description="MCP server name (e.g., 'linear-server', 'plugin:sentry:sentry')"
        ),
    ]
    toolName: Annotated[str, Field(description="MCP tool name")]
    elapsedTimeMs: Annotated[
        int | None,
        Field(description="Elapsed time (present on completed/failed)", ge=0),
    ] = None


class BashProgressData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["bash_progress"]
    output: Annotated[str, Field(description="Truncated stdout/stderr")]
    fullOutput: Annotated[str, Field(description="Full stdout/stderr")]
    elapsedTimeSeconds: Annotated[int, Field(ge=0)]
    totalLines: Annotated[int, Field(ge=0)]
    totalBytes: Annotated[
        int | None, Field(description="Total bytes (background tasks)", ge=0)
    ] = None
    taskId: Annotated[str | None, Field(description="Background task ID")] = None
    timeoutMs: Annotated[int | None, Field(description="Configured timeout", ge=0)] = (
        None
    )


class HookEvent(Enum):
    PreToolUse = "PreToolUse"
    PostToolUse = "PostToolUse"
    SessionStart = "SessionStart"
    SubagentStop = "SubagentStop"
    Stop = "Stop"


class HookProgressData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["hook_progress"]
    hookEvent: Annotated[HookEvent, Field(description="Hook event type")]
    hookName: Annotated[str, Field(description="Hook name (e.g., 'PostToolUse:Grep')")]
    command: Annotated[str, Field(description="Hook command")]


class AgentProgressData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["agent_progress"]
    agentId: Annotated[str, Field(description="Subagent ID")]
    prompt: Annotated[str, Field(description="Task prompt (may be truncated)")]
    normalizedMessages: Annotated[
        list[Any] | None, Field(description="Accumulated subagent messages")
    ] = None
    message: Annotated[
        dict[str, Any] | None,
        Field(description="Full conversation message sent to subagent"),
    ] = None


class TaskType(Enum):
    local_bash = "local_bash"
    local_agent = "local_agent"


class WaitingForTaskData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["waiting_for_task"]
    taskDescription: str
    taskType: Annotated[TaskType, Field(description="Background task type")]


class QueryUpdateData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["query_update"]
    query: Annotated[str, Field(description="Search query submitted")]


class SearchResultsReceivedData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["search_results_received"]
    resultCount: Annotated[int, Field(ge=0)]
    query: str


class ProgressData(
    RootModel[
        MCPProgressData
        | BashProgressData
        | HookProgressData
        | AgentProgressData
        | WaitingForTaskData
        | QueryUpdateData
        | SearchResultsReceivedData
    ]
):
    root: Annotated[
        MCPProgressData
        | BashProgressData
        | HookProgressData
        | AgentProgressData
        | WaitingForTaskData
        | QueryUpdateData
        | SearchResultsReceivedData,
        Field(description="Progress event data — discriminated by data.type"),
    ]


class ProgressMessage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["progress"]
    uuid: UUID
    sessionId: UUID
    parentUuid: UUID | None
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: str
    gitBranch: str | None = None
    isSidechain: bool
    userType: Literal["external"]
    slug: Annotated[
        str | None, Field(description="Human-readable session name (may be absent)")
    ] = None
    agentId: Annotated[
        str | None, Field(description="Agent ID (in subagent session files)")
    ] = None
    toolUseID: Annotated[str | None, Field(description="Associated tool use ID")] = None
    parentToolUseID: Annotated[
        str | None, Field(description="Parent tool use ID (for nested tool calls)")
    ] = None
    data: ProgressData


class PRLinkMessage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["pr-link"]
    sessionId: UUID
    prNumber: Annotated[int, Field(description="Pull request number", ge=1)]
    prUrl: Annotated[AnyUrl, Field(description="Full PR URL")]
    prRepository: Annotated[
        str, Field(description="Repository identifier (e.g., 'owner/repo')")
    ]
    timestamp: ISO8601Timestamp


class ClaudeCodeSessionSchemaV2163(
    RootModel[
        UserMessage
        | AssistantMessage
        | SystemMessage
        | SummaryMessage
        | FileHistorySnapshot
        | QueueOperation
        | ProgressMessage
        | PRLinkMessage
    ]
):
    root: Annotated[
        UserMessage
        | AssistantMessage
        | SystemMessage
        | SummaryMessage
        | FileHistorySnapshot
        | QueueOperation
        | ProgressMessage
        | PRLinkMessage,
        Field(
            description="Schema for Claude Code CLI session JSONL format. Each line in a .jsonl file should validate against this schema. Covers CLI versions 2.1.2 through 2.1.63.",
            title="Claude Code Session Schema (v2.1.63)",
        ),
    ]
