# generated by datamodel-codegen:
#   filename:  .session_noid.schema.json
#   timestamp: 2026-03-02T17:48:43+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class UUID(
    RootModel[
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    ) = Field(..., description='UUID v4 format')


class ISO8601Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(..., description='ISO-8601 timestamp')


class CLIVersion(RootModel[constr(pattern=r'^\d+\.\d+\.\d+$')]):
    root: constr(pattern=r'^\d+\.\d+\.\d+$') = Field(
        ...,
        description='CLI version string (semver)',
        examples=['2.0.62', '2.0.76', '2.1.1', '2.1.59'],
    )


class ModelId(RootModel[str]):
    root: str = Field(
        ...,
        description='Claude model identifier',
        examples=[
            'claude-opus-4-5-20251101',
            'claude-opus-4-6',
            'claude-sonnet-4-5-20250929',
            'claude-sonnet-4-6',
            'claude-haiku-4-5-20251001',
            '<synthetic>',
        ],
    )


class BuiltInToolName(Enum):
    Bash = 'Bash'
    Read = 'Read'
    Write = 'Write'
    Edit = 'Edit'
    Glob = 'Glob'
    Grep = 'Grep'
    WebSearch = 'WebSearch'
    WebFetch = 'WebFetch'
    Task = 'Task'
    TaskOutput = 'TaskOutput'
    TaskStop = 'TaskStop'
    TaskCreate = 'TaskCreate'
    TaskUpdate = 'TaskUpdate'
    TaskList = 'TaskList'
    TaskGet = 'TaskGet'
    TodoWrite = 'TodoWrite'
    AskUserQuestion = 'AskUserQuestion'
    NotebookEdit = 'NotebookEdit'
    EnterPlanMode = 'EnterPlanMode'
    ExitPlanMode = 'ExitPlanMode'
    EnterWorktree = 'EnterWorktree'
    Skill = 'Skill'
    KillShell = 'KillShell'
    ToolSearch = 'ToolSearch'
    SendMessage = 'SendMessage'
    TeamCreate = 'TeamCreate'
    TeamDelete = 'TeamDelete'
    ListMcpResourcesTool = 'ListMcpResourcesTool'
    ReadMcpResourceTool = 'ReadMcpResourceTool'


class MCPToolName(RootModel[constr(pattern=r'^mcp__[a-zA-Z0-9_:-]+__[a-zA-Z0-9_-]+$')]):
    root: constr(pattern=r'^mcp__[a-zA-Z0-9_:-]+__[a-zA-Z0-9_-]+$') = Field(
        ...,
        description='MCP tool name pattern: mcp__<server>__<tool>. Server names may contain colons (e.g., plugin:sentry:sentry).',
    )


class ToolName(RootModel[BuiltInToolName | MCPToolName]):
    root: BuiltInToolName | MCPToolName = Field(
        ..., description='Tool name (built-in or MCP)'
    )


class BashInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: str = Field(..., description='The bash command to execute')
    description: str | None = Field(
        None, description='Short description of command purpose'
    )
    timeout: confloat(ge=0.0, le=600000.0) | None = Field(
        None, description='Timeout in milliseconds'
    )
    run_in_background: bool | None = Field(
        None, description='Run command in background'
    )
    dangerouslyDisableSandbox: bool | None = Field(
        None, description='Disable sandbox mode'
    )


class ReadInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_path: str = Field(..., description='Absolute path to file')
    offset: conint(ge=0) | None = Field(
        None, description='Line number to start reading from'
    )
    limit: conint(ge=1) | None = Field(None, description='Number of lines to read')
    pages: str | None = Field(
        None, description="Page range for PDF files (e.g., '1-5')"
    )


class WriteInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_path: str = Field(..., description='Absolute path to file')
    content: str = Field(..., description='Content to write')


class EditInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_path: str = Field(..., description='Absolute path to file')
    old_string: str = Field(..., description='Text to replace')
    new_string: str = Field(..., description='Replacement text')
    replace_all: bool | None = Field(False, description='Replace all occurrences')


class GlobInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pattern: str = Field(..., description='Glob pattern to match')
    path: str | None = Field(None, description='Directory to search in')


class OutputMode(Enum):
    content = 'content'
    files_with_matches = 'files_with_matches'
    count = 'count'


class GrepInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pattern: str = Field(..., description='Regex pattern to search')
    path: str | None = Field(None, description='File or directory to search')
    output_mode: OutputMode | None = None
    glob: str | None = Field(None, description='Glob pattern to filter files')
    type: str | None = Field(None, description='File type to search (e.g., js, py)')
    head_limit: conint(ge=0) | None = Field(None, description='Limit output lines')
    offset: conint(ge=0) | None = Field(None, description='Skip first N lines')
    multiline: bool | None = Field(None, description='Enable multiline mode')
    context: conint(ge=0) | None = Field(
        None, description='Lines of context (alias for -C)'
    )
    field_A: conint(ge=0) | None = Field(
        None, alias='-A', description='Lines after match'
    )
    field_B: conint(ge=0) | None = Field(
        None, alias='-B', description='Lines before match'
    )
    field_C: conint(ge=0) | None = Field(
        None, alias='-C', description='Lines of context'
    )
    field_i: bool | None = Field(None, alias='-i', description='Case insensitive')
    field_n: bool | None = Field(None, alias='-n', description='Show line numbers')


class WebSearchInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=2) = Field(..., description='Search query')
    allowed_domains: list[str] | None = Field(None, description='Domains to include')
    blocked_domains: list[str] | None = Field(None, description='Domains to exclude')


class WebFetchInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: AnyUrl = Field(..., description='URL to fetch')
    prompt: str = Field(..., description='Prompt for processing content')


class Model(Enum):
    sonnet = 'sonnet'
    opus = 'opus'
    haiku = 'haiku'


class Mode(Enum):
    acceptEdits = 'acceptEdits'
    bypassPermissions = 'bypassPermissions'
    default = 'default'
    dontAsk = 'dontAsk'
    plan = 'plan'


class Isolation(Enum):
    worktree = 'worktree'


class TaskInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str = Field(..., description='Short task description (3-5 words)')
    prompt: str = Field(..., description='Task prompt for agent')
    subagent_type: str = Field(
        ..., description='Type of agent to use (e.g., general-purpose, Explore, Plan)'
    )
    run_in_background: bool | None = Field(None, description='Run agent in background')
    model: Model | None = Field(None, description='Model override for subagent')
    resume: str | None = Field(None, description='Agent ID to resume')
    name: str | None = Field(
        None,
        description='Named agent identifier (used with team_name for team members)',
    )
    team_name: str | None = Field(
        None, description='Team to join (links to TeamCreate)'
    )
    mode: Mode | None = Field(None, description='Permission mode for spawned agent')
    max_turns: conint(le=9007199254740991, gt=0) | None = Field(
        None, description='Max agentic turns before stopping'
    )
    isolation: Isolation | None = Field(
        None, description='Isolation mode — worktree creates a temporary git worktree'
    )


class Status(Enum):
    pending = 'pending'
    in_progress = 'in_progress'
    completed = 'completed'


class TodoItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: constr(min_length=1) = Field(
        ..., description='Task description (imperative form)'
    )
    status: Status
    activeForm: constr(min_length=1) = Field(..., description='Present continuous form')


class TodoWriteInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    todos: list[TodoItem] = Field(..., description='Updated todo list')


class QuestionOption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str = Field(..., description='Display text for option')
    description: str = Field(..., description='Explanation of option')
    markdown: str | None = Field(
        None, description='Preview content shown when option is focused'
    )


class Question(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    question: str = Field(..., description='The question to ask')
    header: constr(max_length=12) = Field(..., description='Short label (max 12 chars)')
    options: list[QuestionOption] = Field(..., max_length=4, min_length=2)
    multiSelect: bool


class Annotations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    markdown: str | None = Field(
        None, description='Markdown preview content of the selected option'
    )
    notes: str | None = Field(
        None, description='Free-text notes the user added to their selection'
    )


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str | None = Field(None, description="Source identifier (e.g., 'remember')")


class AskUserQuestionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    questions: list[Question] = Field(..., max_length=4, min_length=1)
    answers: dict[str, str] | None = Field(None, description='User answers')
    annotations: dict[str, Annotations] | None = Field(
        None, description='Per-question annotations keyed by question text'
    )
    metadata: Metadata | None = Field(None, description='Tracking/analytics metadata')


class CellType(Enum):
    code = 'code'
    markdown = 'markdown'


class EditMode(Enum):
    replace = 'replace'
    insert = 'insert'
    delete = 'delete'


class NotebookEditInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    notebook_path: str = Field(..., description='Absolute path to notebook')
    new_source: str = Field(..., description='New cell source')
    cell_id: str | None = Field(None, description='Cell ID to edit')
    cell_type: CellType | None = None
    edit_mode: EditMode | None = None


class EnterPlanModeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


class Tool(Enum):
    Bash = 'Bash'


class AllowedPrompt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Tool = Field(..., description='Tool this prompt applies to')
    prompt: str = Field(..., description='Semantic description of the allowed action')


class ExitPlanModeInput(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    plan: str | None = Field(None, description='Plan content')
    allowedPrompts: list[AllowedPrompt] | None = Field(
        None, description='Prompt-based permissions needed to implement the plan'
    )


class SkillInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    skill: str = Field(..., description='Skill name to invoke')
    args: str | None = Field(None, description='Optional arguments')


class KillShellInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    shell_id: str = Field(..., description='ID of shell to kill')


class TaskOutputInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str = Field(..., description='Task ID to get output from')
    block: bool = Field(..., description='Wait for completion')
    timeout: confloat(ge=0.0, le=600000.0) = Field(
        ..., description='Max wait time in ms'
    )


class TaskStopInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str | None = Field(None, description='Background task ID to stop')
    shell_id: str | None = Field(None, description='Deprecated: use task_id instead')


class ToolSearchInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: str = Field(
        ..., description="Keyword search or 'select:<tool_name>' for direct selection"
    )
    max_results: confloat(ge=1.0) = Field(..., description='Maximum results to return')


class Type(Enum):
    message = 'message'
    broadcast = 'broadcast'
    shutdown_request = 'shutdown_request'
    shutdown_response = 'shutdown_response'
    plan_approval_response = 'plan_approval_response'


class SendMessageInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type = Field(..., description='Message type')
    recipient: str | None = Field(
        None,
        description='Agent name of recipient (for message, shutdown_request, plan_approval_response)',
    )
    content: str | None = Field(None, description='Message text, reason, or feedback')
    summary: str | None = Field(
        None,
        description='5-10 word summary shown as UI preview (for message, broadcast)',
    )
    request_id: str | None = Field(
        None,
        description='Request ID to respond to (for shutdown_response, plan_approval_response)',
    )
    approve: bool | None = Field(
        None,
        description='Whether to approve (for shutdown_response, plan_approval_response)',
    )


class TaskCreateInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    subject: str = Field(..., description='Brief task title (imperative form)')
    description: str = Field(
        ..., description='Detailed description with context and acceptance criteria'
    )
    activeForm: str | None = Field(
        None, description='Present continuous form shown in spinner'
    )
    metadata: dict[str, Any] | None = Field(None, description='Arbitrary metadata')


class Status1(Enum):
    pending = 'pending'
    in_progress = 'in_progress'
    completed = 'completed'
    deleted = 'deleted'


class TaskUpdateInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    taskId: str = Field(..., description='Task ID to update')
    status: Status1 | None = Field(None, description='New task status')
    subject: str | None = Field(None, description='New task title')
    description: str | None = Field(None, description='New task description')
    activeForm: str | None = Field(None, description='Present continuous form')
    owner: str | None = Field(None, description='Agent name to assign')
    metadata: dict[str, Any] | None = Field(None, description='Metadata to merge')
    addBlocks: list[str] | None = Field(None, description='Task IDs this task blocks')
    addBlockedBy: list[str] | None = Field(
        None, description='Task IDs that block this task'
    )


class TaskListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


class TaskGetInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    taskId: str = Field(..., description='Task ID to retrieve')


class TeamCreateInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    team_name: str = Field(..., description='Slug/identifier for the team')
    description: str | None = Field(None, description='Team purpose')
    agent_type: str | None = Field(
        None, description='Role of the calling agent in the team'
    )


class TeamDeleteInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


class EnterWorktreeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, description='Optional name for the worktree')


class ListMcpResourcesInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    server: str | None = Field(None, description='Optional server name to filter by')


class ReadMcpResourceInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    server: str = Field(..., description='MCP server name')
    uri: str = Field(..., description='Resource URI to read')


class MCPToolInput(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )


class ToolInput(
    RootModel[
        BashInput
        | ReadInput
        | WriteInput
        | EditInput
        | GlobInput
        | GrepInput
        | WebSearchInput
        | WebFetchInput
        | TaskInput
        | TaskOutputInput
        | TaskStopInput
        | ToolSearchInput
        | SendMessageInput
        | TaskCreateInput
        | TaskUpdateInput
        | TaskListInput
        | TaskGetInput
        | TeamCreateInput
        | TeamDeleteInput
        | EnterWorktreeInput
        | ListMcpResourcesInput
        | ReadMcpResourceInput
        | TodoWriteInput
        | AskUserQuestionInput
        | NotebookEditInput
        | EnterPlanModeInput
        | ExitPlanModeInput
        | SkillInput
        | KillShellInput
        | MCPToolInput
    ]
):
    root: (
        BashInput
        | ReadInput
        | WriteInput
        | EditInput
        | GlobInput
        | GrepInput
        | WebSearchInput
        | WebFetchInput
        | TaskInput
        | TaskOutputInput
        | TaskStopInput
        | ToolSearchInput
        | SendMessageInput
        | TaskCreateInput
        | TaskUpdateInput
        | TaskListInput
        | TaskGetInput
        | TeamCreateInput
        | TeamDeleteInput
        | EnterWorktreeInput
        | ListMcpResourcesInput
        | ReadMcpResourceInput
        | TodoWriteInput
        | AskUserQuestionInput
        | NotebookEditInput
        | EnterPlanModeInput
        | ExitPlanModeInput
        | SkillInput
        | KillShellInput
        | MCPToolInput
    ) = Field(..., description='Tool-specific input parameters')


class TextBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    text: str


class ThinkingBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['thinking']
    thinking: str = Field(..., description="Claude's reasoning")
    signature: str = Field(..., description='Cryptographic signature (base64)')


class ToolUseCaller(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: str = Field(..., description="Caller type (e.g., 'direct')")


class ToolUseBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tool_use']
    id: constr(pattern=r'^toolu_[a-zA-Z0-9]+$') = Field(..., description='Tool use ID')
    name: ToolName
    input: dict[str, Any] = Field(..., description='Tool-specific input')
    caller: ToolUseCaller | None = None


class ToolReferenceBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tool_reference']
    tool_name: str = Field(..., description='Name of the referenced tool')


class ToolResultContentItem1(BaseModel):
    type: Literal['text']
    text: str


class MediaType(Enum):
    image_png = 'image/png'
    image_jpeg = 'image/jpeg'
    image_gif = 'image/gif'
    image_webp = 'image/webp'


class Source(BaseModel):
    type: Literal['base64']
    media_type: MediaType
    data: str


class ToolResultContentItem2(BaseModel):
    type: Literal['image']
    source: Source


class ToolResultContentItem(
    RootModel[
        str | ToolResultContentItem1 | ToolResultContentItem2 | ToolReferenceBlock
    ]
):
    root: str | ToolResultContentItem1 | ToolResultContentItem2 | ToolReferenceBlock


class ToolResultBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tool_result']
    tool_use_id: constr(pattern=r'^toolu_[a-zA-Z0-9]+$')
    content: str | list[ToolResultContentItem]
    is_error: bool | None = None


class Source1(BaseModel):
    type: Literal['base64']
    media_type: MediaType
    data: str


class ImageBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image']
    source: Source1


class Type1(Enum):
    base64 = 'base64'


class MediaType2(Enum):
    application_pdf = 'application/pdf'


class Source2(BaseModel):
    type: Type1
    media_type: MediaType2
    data: str


class DocumentBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['document']
    source: Source2


class ContentBlock(
    RootModel[
        TextBlock
        | ThinkingBlock
        | ToolUseBlock
        | ToolResultBlock
        | ImageBlock
        | DocumentBlock
        | ToolReferenceBlock
    ]
):
    root: (
        TextBlock
        | ThinkingBlock
        | ToolUseBlock
        | ToolResultBlock
        | ImageBlock
        | DocumentBlock
        | ToolReferenceBlock
    )


class Level(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class ThinkingMetadata(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    level: Level | None = None
    disabled: bool | None = None
    triggers: list[str] | None = None


class CacheCreation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ephemeral_5m_input_tokens: int | None = None
    ephemeral_1h_input_tokens: int | None = None


class ServerToolUse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    web_search_requests: int | None = None
    web_fetch_requests: int | None = None


class UsageInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    input_tokens: conint(ge=0)
    output_tokens: conint(ge=0)
    cache_creation_input_tokens: conint(ge=0) | None = None
    cache_read_input_tokens: conint(ge=0) | None = None
    cache_creation: CacheCreation | None = None
    service_tier: str | None = None
    server_tool_use: ServerToolUse | None = None
    inference_geo: str | None = Field(
        None,
        description="Inference geographic region (e.g., 'not_available', empty string, or null)",
    )
    iterations: list[dict[str, Any]] | None = Field(
        None, description='Iteration details (observed as empty array or null)'
    )
    speed: str | None = Field(
        None, description="Inference speed tier (e.g., 'standard', or null)"
    )


class UserMessageContent(RootModel[str | list[ContentBlock]]):
    root: str | list[ContentBlock] = Field(
        ...,
        description='User message content - string when isCompactSummary, array otherwise',
    )


class Message(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    role: Literal['user']
    content: UserMessageContent


class PermissionMode(Enum):
    default = 'default'
    acceptEdits = 'acceptEdits'
    bypassPermissions = 'bypassPermissions'
    dontAsk = 'dontAsk'
    plan = 'plan'


class UserMessage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['user']
    uuid: UUID
    parentUuid: UUID | None
    sessionId: UUID
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: str = Field(..., description='Current working directory')
    gitBranch: str | None = Field(None, description='Git branch name')
    isSidechain: bool
    userType: Literal['external']
    message: Message
    thinkingMetadata: ThinkingMetadata | None = None
    todos: list[TodoItem] | None = None
    isMeta: bool | None = None
    isCompactSummary: bool | None = Field(
        None, description='When true, content is summary string'
    )
    isVisibleInTranscriptOnly: bool | None = Field(
        None,
        description='Message visible in transcript but not sent to model (v2.1.x+)',
    )
    agentId: str | None = Field(None, description='Agent ID (in agent session files)')
    slug: str | None = Field(None, description='Human-readable session name')
    toolUseResult: dict[str, Any] | str | list[ToolResultContentItem] | None = Field(
        None,
        description='Tool result metadata (v2.1.1+) — can be object, string, or array of content items',
    )
    sourceToolAssistantUUID: UUID | None = Field(
        None, description='UUID of assistant message that triggered tool (v2.1.1+)'
    )
    permissionMode: PermissionMode | None = Field(
        None, description='Active permission mode for this turn (v2.1.x+)'
    )
    teamName: str | None = Field(
        None, description='Team name when operating in a team context (v2.1.x+)'
    )
    imagePasteIds: list[str | int] | None = Field(
        None, description='IDs of pasted images (v2.1.x+)'
    )


class StopReason(Enum):
    end_turn = 'end_turn'
    tool_use = 'tool_use'
    max_tokens = 'max_tokens'
    stop_sequence = 'stop_sequence'


class Message1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    model: ModelId
    id: str = Field(
        ..., description='API message ID (msg_* pattern or UUID for synthetic)'
    )
    type: Literal['message']
    role: Literal['assistant']
    content: list[ContentBlock]
    stop_reason: StopReason | None
    stop_sequence: str | None
    usage: UsageInfo


class AssistantMessage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['assistant']
    uuid: UUID
    parentUuid: UUID | None
    sessionId: UUID
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: str
    gitBranch: str | None = None
    isSidechain: bool
    userType: Literal['external']
    requestId: constr(pattern=r'^req_[a-zA-Z0-9]+$') | None = Field(
        None, description='API request ID'
    )
    message: Message1
    agentId: str | None = None
    slug: str | None = None
    isApiErrorMessage: bool | None = Field(
        None, description='Whether this is an API error message'
    )
    error: str | None = Field(None, description='Error type (e.g., rate_limit)')
    teamName: str | None = Field(
        None, description='Team name when operating in a team context (v2.1.x+)'
    )


class Subtype(Enum):
    local_command = 'local_command'
    turn_duration = 'turn_duration'
    api_error = 'api_error'
    stop_hook_summary = 'stop_hook_summary'
    compact_boundary = 'compact_boundary'
    bridge_status = 'bridge_status'


class Level1(Enum):
    info = 'info'
    warn = 'warn'
    error = 'error'
    suggestion = 'suggestion'


class CompactMetadata(BaseModel):
    trigger: str | None = None
    preTokens: int | None = None


class Cause(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str | None = Field(
        None,
        description='Error code (e.g., ECONNRESET, ConnectionRefused, FailedToOpenSocket)',
    )
    path: str | None = Field(None, description='Request URL')
    errno: int | None = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    cause: Cause | None = None


class Cause1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str | None = Field(
        None, description='Error code (e.g., ConnectionRefused, FailedToOpenSocket)'
    )
    path: str | None = Field(None, description='Request URL path')
    errno: int | None = None


class SystemMessage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['system']
    uuid: UUID
    parentUuid: UUID | None
    sessionId: UUID
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: str
    gitBranch: str | None = None
    isSidechain: bool
    userType: Literal['external']
    subtype: Subtype = Field(
        ..., description='System message subtype. New in v2.1.x: bridge_status.'
    )
    content: str | None = Field(None, description='Message content')
    level: Level1 | None = None
    durationMs: conint(ge=0) | None = Field(
        None, description='Duration in milliseconds'
    )
    isMeta: bool | None = None
    agentId: str | None = None
    slug: str | None = None
    hookCount: int | None = Field(
        None, description='Number of hooks triggered (stop_hook_summary)'
    )
    hookInfos: list[dict[str, Any]] | None = Field(
        None, description='Hook information (stop_hook_summary)'
    )
    hookErrors: list[dict[str, Any] | str] | None = Field(
        None, description='Hook errors (stop_hook_summary)'
    )
    preventedContinuation: bool | None = Field(
        None, description='Whether hook prevented continuation'
    )
    stopReason: str | None = Field(None, description='Reason for stop')
    hasOutput: bool | None = Field(None, description='Whether there is output')
    toolUseID: str | None = Field(None, description='Tool use ID')
    logicalParentUuid: UUID | None = Field(
        None, description='Logical parent UUID (compact_boundary)'
    )
    compactMetadata: CompactMetadata | None = Field(
        None, description='Compact metadata (compact_boundary)'
    )
    teamName: str | None = Field(
        None, description='Team name when in team context (v2.1.x+)'
    )
    error: Error | None = Field(
        None,
        description='Error details (api_error subtype). Contains cause object mirroring the top-level cause field.',
    )
    url: AnyUrl | None = Field(
        None, description='URL for bridge_status subtype (remote control session link)'
    )
    cause: str | Cause1 | None = Field(
        None,
        description='Error cause — string or object with code/path/errno (api_error retry metadata)',
    )
    retryInMs: confloat(ge=0.0) | None = Field(
        None, description='Retry delay in milliseconds (can be fractional)'
    )
    retryAttempt: conint(ge=0) | None = Field(
        None, description='Current retry attempt number'
    )
    maxRetries: conint(ge=0) | None = Field(None, description='Maximum retry attempts')


class SummaryMessage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['summary']
    summary: str = Field(..., description='Human-readable conversation summary')
    leafUuid: UUID = Field(..., description='UUID of last summarized message')


class FileBackupInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    originalContent: str | None = Field(
        None, description='Original file content (legacy)'
    )
    path: str | None = Field(None, description='File path (legacy)')
    backupFileName: str | None = Field(None, description='Backup file identifier')
    version: conint(ge=1) | None = Field(None, description='Backup version number')
    backupTime: ISO8601Timestamp | None = Field(None, description='Backup timestamp')


class Snapshot(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    messageId: UUID
    trackedFileBackups: dict[str, FileBackupInfo] = Field(
        ..., description='Map of file path to backup info'
    )
    timestamp: ISO8601Timestamp


class FileHistorySnapshot(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['file-history-snapshot']
    messageId: UUID
    snapshot: Snapshot
    isSnapshotUpdate: bool


class Operation(Enum):
    enqueue = 'enqueue'
    remove = 'remove'
    dequeue = 'dequeue'
    popAll = 'popAll'


class QueueOperation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['queue-operation']
    operation: Operation
    timestamp: ISO8601Timestamp
    sessionId: UUID
    content: str | None = Field(None, description='Message content (for enqueue)')


class Status2(Enum):
    started = 'started'
    completed = 'completed'
    failed = 'failed'


class MCPProgressData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['mcp_progress']
    status: Status2
    serverName: str = Field(
        ...,
        description="MCP server name (e.g., 'linear-server', 'plugin:sentry:sentry')",
    )
    toolName: str = Field(..., description='MCP tool name')
    elapsedTimeMs: conint(ge=0) | None = Field(
        None, description='Elapsed time (present on completed/failed)'
    )


class BashProgressData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['bash_progress']
    output: str = Field(..., description='Truncated stdout/stderr')
    fullOutput: str = Field(..., description='Full stdout/stderr')
    elapsedTimeSeconds: conint(ge=0)
    totalLines: conint(ge=0)
    totalBytes: conint(ge=0) | None = Field(
        None, description='Total bytes (background tasks)'
    )
    taskId: str | None = Field(None, description='Background task ID')
    timeoutMs: conint(ge=0) | None = Field(None, description='Configured timeout')


class HookEvent(Enum):
    PreToolUse = 'PreToolUse'
    PostToolUse = 'PostToolUse'
    SessionStart = 'SessionStart'
    SubagentStop = 'SubagentStop'
    Stop = 'Stop'


class HookProgressData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['hook_progress']
    hookEvent: HookEvent = Field(..., description='Hook event type')
    hookName: str = Field(..., description="Hook name (e.g., 'PostToolUse:Grep')")
    command: str = Field(..., description='Hook command')


class AgentProgressData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['agent_progress']
    agentId: str = Field(..., description='Subagent ID')
    prompt: str = Field(..., description='Task prompt (may be truncated)')
    normalizedMessages: list[Any] | None = Field(
        None, description='Accumulated subagent messages'
    )
    message: dict[str, Any] | None = Field(
        None, description='Full conversation message sent to subagent'
    )


class TaskType(Enum):
    local_bash = 'local_bash'
    local_agent = 'local_agent'


class WaitingForTaskData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['waiting_for_task']
    taskDescription: str
    taskType: TaskType = Field(..., description='Background task type')


class QueryUpdateData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['query_update']
    query: str = Field(..., description='Search query submitted')


class SearchResultsReceivedData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['search_results_received']
    resultCount: conint(ge=0)
    query: str


class ProgressData(
    RootModel[
        MCPProgressData
        | BashProgressData
        | HookProgressData
        | AgentProgressData
        | WaitingForTaskData
        | QueryUpdateData
        | SearchResultsReceivedData
    ]
):
    root: (
        MCPProgressData
        | BashProgressData
        | HookProgressData
        | AgentProgressData
        | WaitingForTaskData
        | QueryUpdateData
        | SearchResultsReceivedData
    ) = Field(..., description='Progress event data — discriminated by data.type')


class ProgressMessage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['progress']
    uuid: UUID
    sessionId: UUID
    parentUuid: UUID | None
    timestamp: ISO8601Timestamp
    version: CLIVersion
    cwd: str
    gitBranch: str | None = None
    isSidechain: bool
    userType: Literal['external']
    slug: str | None = Field(
        None, description='Human-readable session name (may be absent)'
    )
    agentId: str | None = Field(
        None, description='Agent ID (in subagent session files)'
    )
    toolUseID: str | None = Field(None, description='Associated tool use ID')
    parentToolUseID: str | None = Field(
        None, description='Parent tool use ID (for nested tool calls)'
    )
    data: ProgressData


class PRLinkMessage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['pr-link']
    sessionId: UUID
    prNumber: conint(ge=1) = Field(..., description='Pull request number')
    prUrl: AnyUrl = Field(..., description='Full PR URL')
    prRepository: str = Field(
        ..., description="Repository identifier (e.g., 'owner/repo')"
    )
    timestamp: ISO8601Timestamp


class ClaudeCodeSessionSchemaV2159(
    RootModel[
        UserMessage
        | AssistantMessage
        | SystemMessage
        | SummaryMessage
        | FileHistorySnapshot
        | QueueOperation
        | ProgressMessage
        | PRLinkMessage
    ]
):
    root: (
        UserMessage
        | AssistantMessage
        | SystemMessage
        | SummaryMessage
        | FileHistorySnapshot
        | QueueOperation
        | ProgressMessage
        | PRLinkMessage
    ) = Field(
        ...,
        description='Schema for Claude Code CLI session JSONL format. Each line in a .jsonl file should validate against this schema. Covers CLI versions 2.1.2 through 2.1.59.',
        title='Claude Code Session Schema (v2.1.59)',
    )
